<?php echo $this->messenger( $this->message ); ?>

<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Profile</h2>
    </div>    
</section>
<section class="part white">
    <div class="area">
        <h3 class="left dark-grey-text">Edit profile</h3>
        <h4 class="left dark-grey-text">Personal information</h4>
        <hr />
        <?php $form = $this->form;
              $form->prepare();
              $form->setAttribute('class' , 'admin');
              echo $this->form()->openTag($form); ?>

        <table class="clear" width="100%">
            <tr>
                <td width="50%" class="right">
                    <h5 class="dark-grey-text">Full name</h5>
                </td>
                <td width="50%">
                    <?= $this->formElement( $form->get('full_name') ) ?>
                </td>
            </tr>
            <tr>
                <td width="50%" class="right">
                    <h5 class="dark-grey-text">E-mail</h5>
                </td>
                <td width="50%">
                    <?= $this->formElement( $form->get('email') ) ?>
                </td>
            </tr>
            <tr>
                <td width="50%" class="right">
                    <h5 class="dark-grey-text">Job</h5>
                </td>
                <td width="50%">
                    <?= $this->formElement( $form->get('job') ) ?>
                </td>
            </tr>
            <tr>
                <td width="50%" class="right">
                    <h5 class="dark-grey-text">Description</h5>
                </td>
                <td width="50%">
                    <?= $this->formElement( $form->get('desc') ) ?>
                </td>
            </tr>
            <tr>
                <td class="right">
                    <img id="profile-image" class="bordered" src="<?= $this->basePath( $this->user[0]["img"] ) ?>" />
                </td>
                <td>
                    <?= $this->formElement( $form->get('img') ) ?>
                    <!--
                        Media
                    -->
                    <?=   $this->media( $this->images , $this->basePath("") ); ?>
                </td>
            </tr>
            <tr>
                <td class="right">
                    <h5 class="dark-grey-text">Displayed in team</h5>
                </td>
                <td align="left">
                    <?= $this->formElement( $form->get('displayed') ) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <?= $this->formButton( $form->get('submit') , 'Save' ) ?>
                </td>
            </tr>

        </table>
        <?= $this->form()->closeTag() ?>
    </div>
</section>