<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Messages</h2>
    </div>    
</section>
<section class="part">
    <div class="area">        
        <h3 class="dark-grey-text">Messages sent by users</h3>
    </div>    
</section>
<section class="part grid">
    <?php foreach( $this->messages as $message ) : ?>
        <div class="third grid-item">
            <div class="text-area">
                <div class="tile">
                    <label>message #<?= $message->id ?></label>
                    <div class="tile-subheading">
                        <p class="small dark-grey-text bold"><?= $message->name ?></p>
                    </div>
                    <div class="tile-subheading">
                        <p class="small dark-grey-text bold"><?= $message->email ?></p>
                    </div>
                    <div>
                        <p class="small dark-grey-text"><?= $message->text ?></p>
                    </div>
                    <div class="tile-subheading">
                        <div class="icon-small-cross" onClick="ajax( 'messages' , 'delete' , <?= $message->id ?> , $(this).parent().parent().parent() )"></div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</section>