<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Ideasheet</h2>
    </div>    
</section>
<section class="part black center-align">
    <img src="<?= $this->basePath( 'img/icons/arrow-down.svg' ) ?>" height="20px" class="cursor-pointer">
</section>
<section class="part">
    Ztmavit plochu po otevření formu, vytvořit formulář(add+edit v jednom), po najetí na idea item zobrazit EDIT/DEL, po kliknutí zobrazit obsah
    <div class="idea">
        <div class="circle red"> </div>
        <div class="tail red"> Magic url </div>
    </div>
    
    <div class="idea">
        <div class="circle grey"> </div>
        <div class="tail grey"> Magic url </div>
    </div>
    <?php //foreach( $this->idea as $idea ) : ?>
    
    <?php //endforeach; ?>
</section>