<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Blog</h2>
    </div>    
</section>

<section class="part">
    <div class="area">
        <h3>List of blog posts</h3>
        <?php if( count( $this->posts ) > 0 ) : ?>
            <table class='admin' width='100%'>
                <tr>
                    <th class="thin">#</th>
                    <th>Topic</th>
                    <th>Author</th>
                    <th class="thin" colspan="2">Actions</th>
                </tr>
                <?php foreach( $this->posts as $post ) : ?>
                    <tr>
                        <td><?= $post->id ?></td>
                        <td class="bold"><?= $post->topic ?></td>
                        <td><?= $post->full_name ?></td>
                        <td class="thin"><a href="<?= $this->basePath( "admin/blog/edit/" . $post->id ) ?>"><div class="icon-small-edit"></div></a></td>
                        <td class="thin"><div onClick="ajax( 'blog' , 'delete' , <?= $post->id ?> , $(this).parent().parent() )" class="icon-small-cross"></div></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php else : ?>
            <h4 class="center">None yet :(</h4>
        <?php endif; ?>
    </div>
</section>