<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('E-bchod')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/hover.min.css'))
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/masonry.pkgd.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.imageScroll.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.nicescroll.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

	<meta property="og:title" content="">
	<meta property="og:description" content="">
	<meta property="og:image" content="">
	<meta name="description" content="">
	<meta name="keywords" content="Sleanded">
	<meta name="pagerank" content="1">
	<meta name="srank" content="100">
	<meta name="pagerank refresh" content="daily">
	<meta name="relevance" content="high">
	<meta name="ranking" content="1">
	<meta name="google position" content="1">
	<meta name="penalization" content="disallow">
	<meta name="spam" content="none">
	<meta name="robots" content="all,follow">
        
    </head>
    <body>   
        <div class="page">
            <header> 
            </header>

            <div id="content">
                <?php echo $this->content; ?>
            </div>

            <footer>
                Copyright &copy; Sleanded 2012-2015
            </footer> 
            
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
