<?php echo $this->messenger( $this->message ); ?>

<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Users > Add</h2>
    </div>    
</section>
<section class="part">
    <div class="area">
        <h3 class="left dark-grey-text">Adding a new user</h3>
        <hr />
        <?php  $form = $this->form;
               $form->prepare();
               $form->setAttribute('class' , 'admin');
               echo $this->form()->openTag($form); ?>
        
        <?=    $this->formElement( $form->get('name') ) . 
               $this->formElement( $form->get('email') ) .
               $this->formElement( $form->get('password') ).
               $this->formButton( $form->get('submit') , "add" ) ?>
        
        <?= $this->form()->closeTag() ?>
    </div>
</section>