<?= $this->messenger( $this->message ); ?>

<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Reference > Add</h2>
    </div>    
</section>
<section class="part">
    <div class="area">        
        <h3 class="left dark-grey-text">Adding a reference</h3>
        <hr />
        <?php $form = $this->form;
              $form->prepare();
              $form->setAttribute('class' , 'admin');
              echo $this->form()->openTag($form); ?>
        
        <?=   $this->formElement( $form->get('name') ) .  
              $this->formElement( $form->get('img') ) ?>
        <!--
            Media
        -->
        <?=   $this->media( $images , $this->basePath("") ); ?>
        
        <?=  $this->formElement( $form->get('desc') ) ?>
        <div>
            <?= $this->media( $images , $this->basePath("") , true ); ?>
            <?= $this->formElement( $form->get('text') ) ?>
        </div>
        <?=  $this->formButton( $form->get('submit') , 'Save' ) ?>
             
        <?= $this->form()->closeTag() ?>
    </div>
</section>