<?= $this->messenger( $this->message ); ?>
<?php foreach( $this->project as $project ) { break; } 
      $progressPoints = explode( '|' , $project->progressPoints ); ?>

<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Projects > View</h2>
    </div>    
</section>

<section class="part">
    <div class="area">
        <h3>Project: <?= $project->name ?></h3>
        <h4>Tickets<i class="fa fa-plus-square ticket-window-trigger"></i></h4>
        <hr />
        <div class="ticket-window">
            <div class="top-bar"><i class="fa fa-times ticket-window-trigger"></i></div>
            <div class="heading"><h3 class="center white-text">Add ticket</h3></i></div>
            
            <?php $form = $this->form;
                  $form->prepare();
                  $form->setAttribute('class' , 'admin text-area');
                  echo $this->form()->openTag($form); ?>

            <?=   $this->formElement( $form->get('name') ) .  
                  $this->formElement( $form->get('desc') ) .
                  $this->formElement( $form->get('author_id') ) .
                  $this->formElement( $form->get('project_id') ) .
                  $this->formElement( $form->get('importance') ) ?>

            <?=   $this->formButton( $form->get('submit') , 'Add' ) ?>

            <?=   $this->form()->closeTag() ?>
            
        </div>
        
        <?php if( count( $this->tickets) > 0 ) : ?>
            <ul class="timeline">
                <?php foreach( $this->tickets as $index=>$ticket ) : ?>
                    <li>
                        <div class="<?= $index % 2 == 0 ? "direction-r" : "direction-l" ?>">
                            <div class="flag-wrapper">
                                <span data-resolved="<?= $ticket->resolved ?>" data-id="<?= $ticket->id ?>" class="flag<?= $ticket->assigned_to ? " resolvable" : "" ?>
                                                                                                                       <?= $ticket->resolved ? " resolved" : "" ?>
                                                                                                                       <?= $ticket->importance < 3 ? " low-importance" : "" ?>
                                                                                                                       <?= $ticket->importance > 3 ? " high-importance" : "" ?>"><?= $ticket->name ?></span>
                                <span class="time-wrapper"><span class="time"><?= $this->date( $ticket->time ) ?></span></span>
                                <?php if( $ticket->assigned_to && !$ticket->resolved ) : ?>
                                    <span class="time-wrapper"><span class="time"><strong><?= $ticket->full_name ?></strong></span></span>
                                <?php elseif( $ticket->resolved ) : ?>
                                    <span class="time-wrapper"><span class="time"><strong>Resolved</strong></span></span>
                                    <span class="time-wrapper"><span class="time"><i data-id="<?= $ticket->id ?>" class="fa fa-times remove-ticket"></i></span></span>
                                <?php else : ?>
                                    <span data-id="<?= $ticket->id ?>" data-assign="<?= $this->user_id ?>" class="clickable time-wrapper"><span class="time">Not assigned yet</span></span>
                                <?php endif; ?>
                            </div>
                            <div class="desc"><?= $ticket->desc ?></div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else : ?>
        <h3 class="center">No tickets assigned to this project</h3>
        <?php endif; ?>
        
        <h4>Project info</h4>
        <hr />
        <p class="indent justify big dark-grey-text margin"><?= $project->desc ?></p>
        <p class="big red-text margin"><a target="_blank" href="<?= $this->basePath( "project/progress/" . $project->id . "/" . $this->urlParser( $project->name ) ) ?>">View page</a></p>
        <h4>Progress</h4>
        <hr />
        <div class="progress-bar stripped" data-percent="<?= ( $project->progress + 1 ) / ( count( $progressPoints ) + 1 ) * 100 ?>%">
            <div><label>Project progress</label></div>    
        </div>
        <ul class="progress-menu">
            <?php foreach( $progressPoints as $index=>$point ) : ?>
                <?php if( $index < $project->progress ) : ?>
                    <li data-change="<?= $index ?>" class="big done"><i class="fa-li fa fa-check-square"></i><?= $point ?></li>
                <?php elseif( $index == $project->progress ) : ?>
                    <li data-change="<?= $index ?>" class="big bold processing"><i class="fa-li fa fa-spinner fa-spin"></i><?= $point ?></li>
                <?php else : ?>
                    <li data-change="<?= $index ?>" class="big waiting"><i class="fa-li fa fa-square"></i><?= $point ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if( $project->progress == count( $progressPoints ) ) : ?>
                    <li data-done="done" data-change="<?= $index + 1 ?>" class="big bold done"><i class="fa-li fa fa-check-square"></i>Done!</li>
            <?php else : ?>
                    <li data-done="done" data-change="<?= $index + 1  ?>" class="big waiting"><i class="fa-li fa fa-square"></i>Done!</li>
            <?php endif;?>
        </ul>
        <h4>Deadline</h4>
        <hr />
        <h3 class="center red-text"><?= $this->date( $project->deadline )?></h3>

    </div>
</section>
<script>
    $("tr").click( function() {
        if( ( href = $(this).data("href") ) !== '' ) {
            location.href = href;
        }
    });
    $(".progress-menu li").click( function() {
        if( ( change = $(this).data("change") ) !== '' ) {
            ajax( 'projects' , 'changeprogress' , "<?= $project->id ?>/" + change , undefined , true );
            
            $(".progress-menu li").each( function() {
                if( $(this).data("change") < change ) {
                    $(this).removeAttr('class').addClass('big done');
                    $(this).find("i").first().remove();
                    $(this).prepend('<i class="fa-li fa fa-check-square"></i>');
                } else if( $(this).data("change") === change ) {
                    if( $(this).data("done") === "done" ) {
                        $(this).removeAttr('class').addClass('big bold done');
                        $(this).find("i").first().remove();
                        $(this).prepend('<i class="fa-li fa fa-check-square"></i>');
                    } else {
                        $(this).removeAttr('class').addClass('big bold processing');
                        $(this).find("i").first().remove();
                        $(this).prepend('<i class="fa-li fa fa-spinner fa-spin"></i>');
                    }
                } else {
                    $(this).removeAttr('class').addClass('big waiting');
                    $(this).find("i").first().remove();
                    $(this).prepend('<i class="fa-li fa fa-square"></i>');
                }
            });
            percent = ( change + 1 ) / $(".progress-menu li").length * 100;
            $(".progress-bar div").animate({width: percent + '%'});
        }
    });
    
    $(".ticket-window-trigger").click(function(){
        $(".ticket-window").fadeToggle();
    });
    
    $(".flag.resolvable").click( function(e) {
        if(e.offsetX < 0 || e.offsetX - this.offsetWidth > 150 ) {
            id = $(this).data("id");
            resolved = $(this).data("resolved") ? 0 : 1;
            
            ajax( 'projects' , 'changeresolved' , id + "/" + resolved , null , true );
            if(  $(this).hasClass('resolved') )
                $(this).removeClass('resolved');
            else
                $(this).addClass('resolved');
        }
    });
    $(".clickable.time-wrapper").click(function(){
        id = $(this).data("id");
        assignTo = $(this).data("assign");
        ajax( 'projects' , 'assignticket' , id + "/" +  assignTo , null , true );
        $(this).children().first().text("Assigned!");
        $(this).removeClass("clickable");
    });
    $(".fa.remove-ticket").click(function(){
        id = $(this).data("id");
        ajax( 'projects' , 'deleteticket' , id , $(this).parent().parent().parent().parent().parent() );
    });
</script>